apiVersion: v1
kind: Template
labels:
  demo: template-buildimage
metadata:
  annotations:
    description: template-buildimage
  name: ${APP_NAME}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
      application: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ${CONTEXTDIR_TEMPL}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      sourceSecret:
        name: githubpusher
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: eliminarL
          value: eliminar
        from:
          kind: ImageStreamTag
          name: dotnet:2.2
          namespace: openshift
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
parameters:
- displayName: Application name
  name: APP_NAME
  required: true
- description: Git source URI for application
  displayName: Git source repository
  name: GIT_URI
  value: https://github.com/gditrani269/s2i-dotnetcore-ex.git
- displayName: Git branch/tag reference
  name: GIT_REF
  required: true
- displayName: ContexDir
  name: CONTEXTDIR_TEMPL
  required: true
