apiVersion: v1
kind: Template
metadata:
  annotations:
    description: template de generacion de pipelines
  name: pipe-${APP_NAME}
labels:
  demo: pipe-t${APP_NAME}
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: pipe-${APP_NAME}
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: https://github.com/gditrani269/OS-Pipeline-Gen.git
        ref: master
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile-new-pipeline
parameters:
- description: Name of the App
  displayName: App Name
  name: APP_NAME
- description: Uri of project
  displayName: Project Uri
  name: GIT_URL
