apiVersion: v1
kind: Template
metadata:
  annotations:
    description: template de generacion de pipelines
  name: pipeline-gen
labels:
  demo: pipe-template-ger
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: pipe-template-ger
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: https://github.com/gditrani269/OS-Pipeline-Gen.git
        ref: master
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
