apiVersion: template.openshift.io/v1
kind: Template
labels:
  demo: pepelui
metadata:
  annotations:
    description: template de generacion de pipelines
  name: pipeline-gen
parameters:
- description: Name of the App
  displayName: App Name
  name: APP_NAME
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
   name: pepelui
spec:
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        node {
          stage('holis') {
            sh "echo test 1"
          }
          stage('input ') {
            sh 'echo hola'
            script {
                 def userInput = input(
                 id: 'userInput', message: 'Enter path of test reports:?', 
                 parameters: [
                 [$class: 'TextParameterDefinition', defaultValue: 'None', description: 'Ingrese la url del repositorio', name: 'GIT_URL'],
                 [$class: 'TextParameterDefinition', defaultValue: 'None', description: 'Ingrese el nombre de la aplicacion', name: 'APP_NAME']
                ])
                echo "La URL del repo es: "+userInput['GIT_URL']
                echo "El nombre de la app es: "+userInput['APP_NAME']
                sh 'oc new-app -p APP_NAME=' + userInput['APP_NAME'] + ' -f https://github.com/gditrani269/OS-Pipeline-Gen/blob/master/Pipeline-Template.yaml'
            }
          }
        }  
