kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: ${SERVICE_NAME}
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: "node('agent') {\nstage 'build'\nopenshiftBuild(buildConfig: 'ruby-sample-build', showBuildLogs: 'true')\nstage 'deploy'\nopenshiftDeploy(deploymentConfig: 'frontend')\n}"
parameters:
- description: Name of the service
  displayName: Service Name
  name: SERVICE_NAME
- description: Git repository where service is stored
  displayName: GIT Service URL
  name: SERVICE_GIT_URL
